#!/usr/bin/env python3
"""Generate js/characters.js with pinyin and meanings for all bundled characters."""
import json, os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT       = os.path.dirname(SCRIPT_DIR)
BUNDLE_JS  = os.path.join(ROOT, 'js', 'char-data-bundle.js')
OUT        = os.path.join(ROOT, 'js', 'characters.js')

# ── Master lookup: char → (pinyin, meaning) ───────────────────────────────
LOOKUP = {
    # Numbers
    "一": ("yī",   "one"),
    "二": ("èr",   "two"),
    "三": ("sān",  "three"),
    "四": ("sì",   "four"),
    "五": ("wǔ",   "five"),
    "六": ("liù",  "six"),
    "七": ("qī",   "seven"),
    "八": ("bā",   "eight"),
    "九": ("jiǔ",  "nine"),
    "十": ("shí",  "ten"),
    "百": ("bǎi",  "hundred"),
    "千": ("qiān", "thousand"),
    "万": ("wàn",  "ten thousand"),
    "零": ("líng", "zero"),
    # Basic nouns
    "人": ("rén",   "person"),
    "大": ("dà",    "big"),
    "小": ("xiǎo",  "small"),
    "中": ("zhōng", "middle / China"),
    "上": ("shàng", "up / above"),
    "下": ("xià",   "down / below"),
    "口": ("kǒu",   "mouth"),
    "日": ("rì",    "sun / day"),
    "月": ("yuè",   "moon / month"),
    "年": ("nián",  "year"),
    "时": ("shí",   "time / hour"),
    "天": ("tiān",  "sky / day"),
    "地": ("dì",    "earth / ground"),
    "国": ("guó",   "country"),
    "家": ("jiā",   "home / family"),
    "学": ("xué",   "study / learn"),
    "校": ("xiào",  "school"),
    "生": ("shēng", "born / student"),
    "老": ("lǎo",   "old / elderly"),
    "力": ("lì",    "strength / power"),
    "心": ("xīn",   "heart / mind"),
    "手": ("shǒu",  "hand"),
    "目": ("mù",    "eye"),
    "文": ("wén",   "writing / language"),
    "字": ("zì",    "character / word"),
    "名": ("míng",  "name / famous"),
    "事": ("shì",   "matter / thing"),
    "方": ("fāng",  "direction / square"),
    "面": ("miàn",  "face / surface"),
    "头": ("tóu",   "head"),
    "里": ("lǐ",    "inside / mile"),
    "身": ("shēn",  "body / self"),
    "气": ("qì",    "air / breath / spirit"),
    "水": ("shuǐ",  "water"),
    "火": ("huǒ",   "fire"),
    "木": ("mù",    "wood / tree"),
    "金": ("jīn",   "gold / metal"),
    "山": ("shān",  "mountain"),
    "田": ("tián",  "field / farm"),
    "花": ("huā",   "flower"),
    "草": ("cǎo",   "grass"),
    "树": ("shù",   "tree"),
    "雨": ("yǔ",    "rain"),
    "雪": ("xuě",   "snow"),
    "风": ("fēng",  "wind"),
    "云": ("yún",   "cloud"),
    "光": ("guāng", "light"),
    "星": ("xīng",  "star"),
    "石": ("shí",   "stone / rock"),
    "土": ("tǔ",    "earth / soil"),
    "鱼": ("yú",    "fish"),
    "鸟": ("niǎo",  "bird"),
    "牛": ("niú",   "cow / ox"),
    "马": ("mǎ",    "horse"),
    "羊": ("yáng",  "sheep / goat"),
    "鸡": ("jī",    "chicken"),
    "猫": ("māo",   "cat"),
    "狗": ("gǒu",   "dog"),
    "虫": ("chóng", "insect / bug"),
    "叶": ("yè",    "leaf"),
    "果": ("guǒ",   "fruit / result"),
    "根": ("gēn",   "root"),
    "茶": ("chá",   "tea"),
    "米": ("mǐ",    "rice / meter"),
    "路": ("lù",    "road / path"),
    "门": ("mén",   "door / gate"),
    "房": ("fáng",  "room / house"),
    "车": ("chē",   "car / vehicle"),
    "书": ("shū",   "book"),
    "音": ("yīn",   "sound / music"),
    "乐": ("lè",    "happy / music"),
    "语": ("yǔ",    "language"),
    "汉": ("hàn",   "Han Chinese"),
    "英": ("yīng",  "English / hero"),
    "数": ("shù",   "number / math"),
    "电": ("diàn",  "electricity"),
    "话": ("huà",   "speech / talk"),
    "工": ("gōng",  "work / labor"),
    "色": ("sè",    "color"),
    "点": ("diǎn",  "point / dot / a bit"),
    "线": ("xiàn",  "line / thread"),
    "角": ("jiǎo",  "angle / corner"),
    "圆": ("yuán",  "circle / round"),
    "半": ("bàn",   "half"),
    # Pronouns & particles
    "我": ("wǒ",   "I / me"),
    "你": ("nǐ",   "you"),
    "他": ("tā",   "he / him"),
    "她": ("tā",   "she / her"),
    "它": ("tā",   "it"),
    "们": ("men",  "plural suffix"),
    "的": ("de",   "particle (possessive)"),
    "了": ("le",   "particle (completion)"),
    "在": ("zài",  "at / in / exist"),
    "是": ("shì",  "to be / is"),
    "有": ("yǒu",  "have / there is"),
    "和": ("hé",   "and / with"),
    "就": ("jiù",  "just / then"),
    "也": ("yě",   "also / too"),
    "都": ("dōu",  "all / both"),
    "很": ("hěn",  "very"),
    "最": ("zuì",  "most"),
    "还": ("hái",  "still / also"),
    "再": ("zài",  "again"),
    "又": ("yòu",  "again / both"),
    "已": ("yǐ",   "already"),
    "被": ("bèi",  "by (passive marker)"),
    "让": ("ràng", "let / allow"),
    "把": ("bǎ",   "hold / particle"),
    "给": ("gěi",  "give / for"),
    "从": ("cóng", "from"),
    "到": ("dào",  "arrive / to"),
    "对": ("duì",  "correct / toward"),
    "与": ("yǔ",   "and / with"),
    "或": ("huò",  "or"),
    "而": ("ér",   "and / but"),
    "但": ("dàn",  "but"),
    "因": ("yīn",  "because"),
    "所": ("suǒ",  "place / so"),
    "为": ("wéi",  "for / because"),
    "以": ("yǐ",   "with / by"),
    "按": ("àn",   "press / according to"),
    "如": ("rú",   "as / like"),
    "何": ("hé",   "what / how"),
    "其": ("qí",   "its / that"),
    "之": ("zhī",  "particle (literary)"),
    "乎": ("hū",   "question particle"),
    # Verbs
    "说": ("shuō", "say / speak"),
    "看": ("kàn",  "look / watch"),
    "想": ("xiǎng","think / want"),
    "知": ("zhī",  "know"),
    "道": ("dào",  "way / road"),
    "会": ("huì",  "can / know how"),
    "能": ("néng", "can / able to"),
    "要": ("yào",  "want / need"),
    "用": ("yòng", "use"),
    "做": ("zuò",  "do / make"),
    "吃": ("chī",  "eat"),
    "喝": ("hē",   "drink"),
    "睡": ("shuì", "sleep"),
    "跑": ("pǎo",  "run"),
    "走": ("zǒu",  "walk / go"),
    "坐": ("zuò",  "sit"),
    "站": ("zhàn", "stand / station"),
    "开": ("kāi",  "open / start"),
    "关": ("guān", "close / off"),
    "写": ("xiě",  "write"),
    "听": ("tīng", "listen"),
    "问": ("wèn",  "ask"),
    "答": ("dá",   "answer"),
    "教": ("jiāo", "teach"),
    "买": ("mǎi",  "buy"),
    "卖": ("mài",  "sell"),
    "送": ("sòng", "send / deliver"),
    "拿": ("ná",   "take / hold"),
    "打": ("dǎ",   "hit / beat / call"),
    "叫": ("jiào", "call / shout"),
    "找": ("zhǎo", "look for"),
    "带": ("dài",  "bring / belt"),
    "放": ("fàng", "put / release"),
    "进": ("jìn",  "enter"),
    "出": ("chū",  "exit / out"),
    "回": ("huí",  "return"),
    "过": ("guò",  "pass / over"),
    "起": ("qǐ",   "rise / start"),
    "来": ("lái",  "come"),
    "去": ("qù",   "go"),
    "见": ("jiàn", "see / meet"),
    "读": ("dú",   "read"),
    "画": ("huà",  "draw / painting"),
    "唱": ("chàng","sing"),
    "玩": ("wán",  "play"),
    "跳": ("tiào", "jump / dance"),
    "笑": ("xiào", "laugh / smile"),
    "哭": ("kū",   "cry"),
    "感": ("gǎn",  "feel / sense"),
    "爱": ("ài",   "love"),
    "恨": ("hèn",  "hate"),
    "帮": ("bāng", "help"),
    "告": ("gào",  "tell / inform"),
    "诉": ("sù",   "tell / accuse"),
    "请": ("qǐng", "please / invite"),
    "谢": ("xiè",  "thank"),
    "拜": ("bài",  "worship / visit"),
    "祝": ("zhù",  "wish / celebrate"),
    "希": ("xī",   "hope"),
    "望": ("wàng", "hope / look"),
    "相": ("xiāng","mutual / each other"),
    "信": ("xìn",  "believe / letter"),
    "试": ("shì",  "try / test"),
    "借": ("jiè",  "borrow / lend"),
    "选": ("xuǎn", "choose / select"),
    "决": ("jué",  "decide"),
    "定": ("dìng", "decide / fixed"),
    "成": ("chéng","become / succeed"),
    "败": ("bài",  "fail / defeat"),
    "赢": ("yíng", "win"),
    "输": ("shū",  "lose"),
    "比": ("bǐ",   "compare / than"),
    "赛": ("sài",  "compete / match"),
    "参": ("cān",  "participate"),
    "加": ("jiā",  "add / join"),
    "始": ("shǐ",  "begin / start"),
    "结": ("jié",  "end / tie"),
    "束": ("shù",  "bundle / end"),
    "完": ("wán",  "finish"),
    "准": ("zhǔn", "accurate / allow"),
    "备": ("bèi",  "prepare"),
    "计": ("jì",   "plan / calculate"),
    "划": ("huá",  "plan / stroke"),
    "安": ("ān",   "peaceful / safe"),
    "排": ("pái",  "arrange / row"),
    "管": ("guǎn", "manage / tube"),
    "理": ("lǐ",   "manage / reason"),
    "解": ("jiě",  "understand / solve"),
    "处": ("chǔ",  "handle / place"),
    "析": ("xī",   "analyze"),
    "研": ("yán",  "research / grind"),
    "究": ("jiū",  "research"),
    "调": ("diào", "investigate / tune"),
    "查": ("chá",  "investigate / check"),
    "发": ("fā",   "send / develop"),
    "现": ("xiàn", "appear / now"),
    "证": ("zhèng","prove / certificate"),
    "明": ("míng", "bright / tomorrow"),
    # Adjectives
    "好": ("hǎo",  "good / well"),
    "不": ("bù",   "not / no"),
    "这": ("zhè",  "this"),
    "那": ("nà",   "that"),
    "多": ("duō",  "many / much"),
    "少": ("shǎo", "few / little"),
    "几": ("jǐ",   "how many / a few"),
    "两": ("liǎng","two (of)"),
    "早": ("zǎo",  "early / morning"),
    "晚": ("wǎn",  "evening / late"),
    "今": ("jīn",  "now / today"),
    "红": ("hóng", "red"),
    "绿": ("lǜ",   "green"),
    "蓝": ("lán",  "blue"),
    "黄": ("huáng","yellow"),
    "白": ("bái",  "white"),
    "黑": ("hēi",  "black"),
    "高": ("gāo",  "tall / high"),
    "低": ("dī",   "low / short"),
    "冷": ("lěng", "cold"),
    "热": ("rè",   "hot"),
    "新": ("xīn",  "new"),
    "快": ("kuài", "fast / quick"),
    "慢": ("màn",  "slow"),
    "长": ("cháng","long"),
    "短": ("duǎn", "short"),
    "重": ("zhòng","heavy / important"),
    "轻": ("qīng", "light / gentle"),
    "硬": ("yìng", "hard / stiff"),
    "软": ("ruǎn", "soft"),
    "甜": ("tián", "sweet"),
    "苦": ("kǔ",   "bitter"),
    "辣": ("là",   "spicy"),
    "咸": ("xián", "salty"),
    "酸": ("suān", "sour"),
    "香": ("xiāng","fragrant / delicious"),
    "臭": ("chòu", "smelly"),
    "亮": ("liàng","bright"),
    "暗": ("àn",   "dark"),
    "美": ("měi",  "beautiful / America"),
    "丑": ("chǒu", "ugly"),
    "错": ("cuò",  "wrong / mistake"),
    "真": ("zhēn", "true / real"),
    "假": ("jiǎ",  "fake / false"),
    "容": ("róng", "contain / allow"),
    "易": ("yì",   "easy"),
    "难": ("nán",  "difficult"),
    "简": ("jiǎn", "simple"),
    "单": ("dān",  "single / simple"),
    "复": ("fù",   "repeat / complex"),
    "杂": ("zá",   "mixed / complex"),
    "趣": ("qù",   "interest / fun"),
    "无": ("wú",   "without / none"),
    "聊": ("liáo", "chat / boring"),
    "健": ("jiàn", "healthy / strong"),
    "康": ("kāng", "health"),
    "全": ("quán", "complete / whole"),
    "危": ("wēi",  "danger"),
    "险": ("xiǎn", "danger /险峻"),
    "普": ("pǔ",   "universal / common"),
    "通": ("tōng", "through / communicate"),
    "特": ("tè",   "special"),
    "别": ("bié",  "other / don't"),
    "样": ("yàng", "manner / kind"),
    "干": ("gān",  "dry / clean"),
    "净": ("jìng", "clean"),
    "脏": ("zāng", "dirty"),
    "整": ("zhěng","whole / tidy"),
    "洁": ("jié",  "clean"),
    "乱": ("luàn", "messy / chaotic"),
    "直": ("zhí",  "straight"),
    "弯": ("wān",  "bend / curve"),
    "平": ("píng", "flat / peaceful"),
    "斜": ("xié",  "slanted / diagonal"),
    "深": ("shēn", "deep"),
    "浅": ("qiǎn", "shallow"),
    # Directions / time
    "前": ("qián", "front / before"),
    "后": ("hòu",  "back / after"),
    "左": ("zuǒ",  "left"),
    "右": ("yòu",  "right"),
    "东": ("dōng", "east"),
    "西": ("xī",   "west"),
    "南": ("nán",  "south"),
    "北": ("běi",  "north"),
    "昨": ("zuó",  "yesterday"),
    "午": ("wǔ",   "noon / midday"),
    "周": ("zhōu", "week / cycle"),
    "秒": ("miǎo", "second (time)"),
    "将": ("jiāng","will / general"),
    "近": ("jìn",  "near / recent"),
    "经": ("jīng", "pass through / classic"),
    "常": ("cháng","often / normal"),
    "偶": ("ǒu",   "occasional / pair"),
    "尔": ("ěr",   "you (literary)"),
    "每": ("měi",  "every / each"),
    "春": ("chūn", "spring"),
    "夏": ("xià",  "summer"),
    "秋": ("qiū",  "autumn / fall"),
    "冬": ("dōng", "winter"),
    "节": ("jié",  "festival / joint"),
    # Places
    "城": ("chéng","city"),
    "市": ("shì",  "city / market"),
    "省": ("shěng","province"),
    "区": ("qū",   "district / area"),
    "街": ("jiē",  "street"),
    "楼": ("lóu",  "building / floor"),
    "层": ("céng", "floor / layer"),
    "室": ("shì",  "room"),
    "院": ("yuàn", "courtyard / institution"),
    "园": ("yuán", "garden / park"),
    "馆": ("guǎn", "hall / building"),
    "店": ("diàn", "shop / store"),
    "场": ("chǎng","place / field"),
    "港": ("gǎng", "harbor / Hong Kong"),
    "机": ("jī",   "machine / aircraft"),
    "医": ("yī",   "medicine / doctor"),
    "银": ("yín",  "silver / bank"),
    "行": ("háng", "business / bank"),
    "超": ("chāo", "exceed / super"),
    "公": ("gōng", "public"),
    "司": ("sī",   "manage / department"),
    "厂": ("chǎng","factory"),
    "农": ("nóng", "agriculture / farmer"),
    "村": ("cūn",  "village"),
    "外": ("wài",  "outside / foreign"),
    "海": ("hǎi",  "sea / ocean"),
    "世": ("shì",  "world / generation"),
    "界": ("jiè",  "boundary / world"),
    "球": ("qiú",  "ball / earth"),
    "宇": ("yǔ",   "universe / space"),
    "宙": ("zhòu", "universe / time"),
    # Family
    "父": ("fù",   "father"),
    "母": ("mǔ",   "mother"),
    "朋": ("péng", "friend"),
    "友": ("yǒu",  "friend"),
    "兄": ("xiōng","older brother"),
    "弟": ("dì",   "younger brother"),
    "姐": ("jiě",  "older sister"),
    "妹": ("mèi",  "younger sister"),
    "儿": ("ér",   "child / son"),
    "女": ("nǚ",   "female / daughter"),
    "夫": ("fū",   "husband"),
    "妻": ("qī",   "wife"),
    "子": ("zǐ",   "child / son"),
    "孙": ("sūn",  "grandchild"),
    "祖": ("zǔ",   "ancestor"),
    "爷": ("yé",   "grandpa / sir"),
    "奶": ("nǎi",  "grandma / milk"),
    "叔": ("shū",  "uncle (father's younger brother)"),
    "伯": ("bó",   "uncle (father's older brother)"),
    "姑": ("gū",   "aunt (father's sister)"),
    "舅": ("jiù",  "uncle (mother's brother)"),
    "婶": ("shěn", "aunt (uncle's wife)"),
    "侄": ("zhí",  "nephew / niece"),
    "婆": ("pó",   "grandma / old woman"),
    # Body
    "脸": ("liǎn", "face"),
    "眼": ("yǎn",  "eye"),
    "耳": ("ěr",   "ear"),
    "鼻": ("bí",   "nose"),
    "嘴": ("zuǐ",  "mouth / beak"),
    "牙": ("yá",   "tooth"),
    "舌": ("shé",  "tongue"),
    "颈": ("jǐng", "neck"),
    "肩": ("jiān", "shoulder"),
    "胸": ("xiōng","chest"),
    "腰": ("yāo",  "waist"),
    "背": ("bèi",  "back"),
    "腿": ("tuǐ",  "leg"),
    "脚": ("jiǎo", "foot"),
    "指": ("zhǐ",  "finger / point"),
    "甲": ("jiǎ",  "nail / first"),
    "皮": ("pí",   "skin / leather"),
    "肤": ("fū",   "skin"),
    "骨": ("gǔ",   "bone"),
    "血": ("xuè",  "blood"),
    "肉": ("ròu",  "meat / flesh"),
    "肺": ("fèi",  "lung"),
    "胃": ("wèi",  "stomach"),
    "脑": ("nǎo",  "brain"),
    "神": ("shén", "spirit / god"),
    # Food
    "饭": ("fàn",  "cooked rice / meal"),
    "菜": ("cài",  "vegetable / dish"),
    "蛋": ("dàn",  "egg"),
    "粥": ("zhōu", "porridge / congee"),
    "汤": ("tāng", "soup"),
    "包": ("bāo",  "bun / bag"),
    "糕": ("gāo",  "cake / pastry"),
    "饼": ("bǐng", "flatbread / cookie"),
    "糖": ("táng", "sugar / candy"),
    "盐": ("yán",  "salt"),
    "油": ("yóu",  "oil"),
    "酱": ("jiàng","sauce"),
    "醋": ("cù",   "vinegar"),
    "蒜": ("suàn", "garlic"),
    "姜": ("jiāng","ginger"),
    "葱": ("cōng", "green onion"),
    "椒": ("jiāo", "pepper"),
    "豆": ("dòu",  "bean"),
    "腐": ("fǔ",   "tofu / rotten"),
    "虾": ("xiā",  "shrimp"),
    "蟹": ("xiè",  "crab"),
    "猪": ("zhū",  "pig"),
    # Clothes
    "衣": ("yī",   "clothes"),
    "服": ("fú",   "clothes / serve"),
    "裤": ("kù",   "pants / trousers"),
    "裙": ("qún",  "skirt"),
    "帽": ("mào",  "hat"),
    "鞋": ("xié",  "shoe"),
    "袜": ("wà",   "sock"),
    "领": ("lǐng", "lead / collar"),
    "袖": ("xiù",  "sleeve"),
    "扣": ("kòu",  "button / fasten"),
    "布": ("bù",   "cloth / fabric"),
    "棉": ("mián", "cotton"),
    # Transport
    "船": ("chuán","boat / ship"),
    "飞": ("fēi",  "fly"),
    "铁": ("tiě",  "iron / railway"),
    "交": ("jiāo", "exchange / traffic"),
    "租": ("zū",   "rent"),
    "摩": ("mó",   "rub / motor"),
    "托": ("tuō",  "hold up / trust"),
    # Education
    "考": ("kǎo",  "test / exam"),
    "绩": ("jì",   "achievement / grade"),
    "功": ("gōng", "achievement / merit"),
    "题": ("tí",   "topic / problem"),
    "案": ("àn",   "case / plan"),
    "作": ("zuò",  "make / work"),
    "业": ("yè",   "occupation / industry"),
    "课": ("kè",   "class / lesson"),
    "堂": ("táng", "hall / classroom"),
    "师": ("shī",  "teacher / master"),
    "同": ("tóng", "same / together"),
    "识": ("shí",  "know / knowledge"),
    "验": ("yàn",  "test / experience"),
    "法": ("fǎ",   "law / method"),
    # Work / economy
    "职": ("zhí",  "position / occupation"),
    "合": ("hé",   "combine / fit"),
    "展": ("zhǎn", "develop / exhibit"),
    "步": ("bù",   "step / pace"),
    "济": ("jì",   "economy / help"),
    "贸": ("mào",  "trade"),
    "价": ("jià",  "price"),
    "格": ("gé",   "grid / standard"),
    "收": ("shōu", "receive / collect"),
    "入": ("rù",   "enter"),
    "支": ("zhī",  "support / branch"),
    "利": ("lì",   "profit / benefit"),
    "润": ("rùn",  "moist / profit"),
    # Nature / environment
    "自": ("zì",   "self / oneself"),
    "然": ("rán",  "natural / right"),
    "环": ("huán", "ring / surround"),
    "境": ("jìng", "boundary / environment"),
    "保": ("bǎo",  "protect"),
    "护": ("hù",   "protect / guard"),
    "资": ("zī",   "resources / capital"),
    "源": ("yuán", "source"),
    "空": ("kōng", "empty / sky"),
    "污": ("wū",   "pollute / dirty"),
    "染": ("rǎn",  "dye / infect"),
    "态": ("tài",  "state / attitude"),
    "候": ("hòu",  "climate / wait"),
    "温": ("wēn",  "warm / temperature"),
    "湿": ("shī",  "wet / humid"),
    "压": ("yā",   "pressure / press"),
    "物": ("wù",   "thing / object"),
    "种": ("zhǒng","kind / species / plant"),
    # Technology
    "网": ("wǎng", "net / internet"),
    "络": ("luò",  "connect / network"),
    "件": ("jiàn", "item / component"),
    "程": ("chéng","journey / procedure"),
    "序": ("xù",   "order / sequence"),
    "据": ("jù",   "according to / data"),
    "息": ("xī",   "rest / news"),
    "科": ("kē",   "science / department"),
    "技": ("jì",   "skill / technology"),
    "创": ("chuàng","create"),
    "智": ("zhì",  "wisdom / intelligent"),
    "器": ("qì",   "device / container"),
    "联": ("lián", "connect / ally"),
    # Health
    "病": ("bìng", "sick / illness"),
    "药": ("yào",  "medicine"),
    "术": ("shù",  "skill / art / surgery"),
    "治": ("zhì",  "govern / treat"),
    "疗": ("liáo", "treat / therapy"),
    "检": ("jiǎn", "check / inspect"),
    "休": ("xiū",  "rest"),
    "运": ("yùn",  "transport / luck"),
    "动": ("dòng", "move"),
    "锻": ("duàn", "forge / exercise"),
    "炼": ("liàn", "smelt / train"),
    "营": ("yíng", "camp / manage"),
    "养": ("yǎng", "raise / nourish"),
    "维": ("wéi",  "maintain"),
    "素": ("sù",   "element / plain"),
    # Common grammar / usage words
    "着": ("zhe",  "particle (ongoing)"),
    "使": ("shǐ",  "make / use"),
    "没": ("méi",  "not have"),
    "系": ("xì",   "system / relate"),
    "怎": ("zěn",  "how"),
    "么": ("me",   "question suffix"),
    "什": ("shén", "what"),
    "哪": ("nǎ",   "which / where"),
    "些": ("xiē",  "some / a few"),
    "个": ("gè",   "individual (measure word)"),
    "共": ("gòng", "together / total"),
    "太": ("tài",  "too / extremely"),
    "非": ("fēi",  "non- / wrong"),
    "极": ("jí",   "extreme / pole"),
    "当": ("dāng", "when / should"),
    "较": ("jiào", "compare / relatively"),
    "挺": ("tǐng", "quite / stand straight"),
    "差": ("chà",  "differ / bad"),
    "度": ("dù",   "degree / measure"),
    "分": ("fēn",  "minute / score / divide"),
}

# Load bundle to get exact set of characters with data
with open(BUNDLE_JS, encoding='utf-8') as f:
    raw = f.read()[len('const CHAR_DATA_BUNDLE = '):-2]
bundle = json.loads(raw)
available = set(bundle.keys())

# Build entries for characters we have both lookup and stroke data
entries = []
for char in bundle.keys():   # preserve bundle order
    if char in LOOKUP:
        pinyin, meaning = LOOKUP[char]
        entries.append((char, pinyin, meaning))

print(f"Characters with full data (stroke + pinyin/meaning): {len(entries)}")
no_lookup = [c for c in available if c not in LOOKUP]
print(f"Characters with stroke data but no lookup entry: {len(no_lookup)}")
if no_lookup:
    print("  Missing:", "".join(no_lookup))

# Generate characters.js
lines = [
    "// Chinese character database with pinyin and English meaning",
    "// Used for search functionality",
    "",
    "const CHARACTERS = [",
]

for char, pinyin, meaning in entries:
    # Escape for JS
    p = pinyin.replace('"', '\\"')
    m = meaning.replace('"', '\\"')
    lines.append(f'  {{ char: "{char}", pinyin: "{p}", meaning: "{m}" }},')

lines += [
    "];",
    "",
    "// Build search index",
    "const PINYIN_INDEX = {};",
    "const CHAR_INDEX = {};",
    "",
    "CHARACTERS.forEach((item, idx) => {",
    "  CHAR_INDEX[item.char] = idx;",
    "  const pinyinNorm = normalizePinyin(item.pinyin);",
    "  if (!PINYIN_INDEX[pinyinNorm]) PINYIN_INDEX[pinyinNorm] = [];",
    "  PINYIN_INDEX[pinyinNorm].push(idx);",
    "  const pinyinKey = item.pinyin.toLowerCase().split(' / ')[0];",
    "  if (!PINYIN_INDEX[pinyinKey]) PINYIN_INDEX[pinyinKey] = [];",
    "  if (!PINYIN_INDEX[pinyinKey].includes(idx)) PINYIN_INDEX[pinyinKey].push(idx);",
    "});",
    "",
    "function normalizePinyin(pinyin) {",
    "  return pinyin.toLowerCase()",
    "    .replace(/[āáǎà]/g, 'a')",
    "    .replace(/[ēéěè]/g, 'e')",
    "    .replace(/[īíǐì]/g, 'i')",
    "    .replace(/[ōóǒò]/g, 'o')",
    "    .replace(/[ūúǔù]/g, 'u')",
    "    .replace(/[ǖǘǚǜ]/g, 'u')",
    "    .split(' / ')[0];",
    "}",
    "",
    "function searchCharacters(query) {",
    "  if (!query || query.trim() === '') return [];",
    "  query = query.trim();",
    "  const results = new Set();",
    "  if (/[\\u4e00-\\u9fff]/.test(query)) {",
    "    const idx = CHAR_INDEX[query];",
    "    if (idx !== undefined) results.add(idx);",
    "  } else {",
    "    const qLower = query.toLowerCase();",
    "    const qNorm = normalizePinyin(qLower);",
    "    CHARACTERS.forEach((item, idx) => {",
    "      const pNorm = normalizePinyin(item.pinyin);",
    "      const pLower = item.pinyin.toLowerCase().split(' / ')[0];",
    "      if (pNorm.startsWith(qNorm) || pLower.startsWith(qLower)) {",
    "        results.add(idx);",
    "      }",
    "    });",
    "  }",
    "  return Array.from(results).map(idx => CHARACTERS[idx]);",
    "}",
    "",
    "// Total character count",
    "const TOTAL_CHARACTERS = CHARACTERS.length;",
    "",
]

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"Written: {OUT} ({len(entries)} characters)")
