// Chinese character database with pinyin and English meaning
// Used for search functionality

const CHARACTERS = [
  { char: "一", pinyin: "yī", meaning: "one" },
  { char: "二", pinyin: "èr", meaning: "two" },
  { char: "三", pinyin: "sān", meaning: "three" },
  { char: "四", pinyin: "sì", meaning: "four" },
  { char: "五", pinyin: "wǔ", meaning: "five" },
  { char: "六", pinyin: "liù", meaning: "six" },
  { char: "七", pinyin: "qī", meaning: "seven" },
  { char: "八", pinyin: "bā", meaning: "eight" },
  { char: "九", pinyin: "jiǔ", meaning: "nine" },
  { char: "十", pinyin: "shí", meaning: "ten" },
  { char: "百", pinyin: "bǎi", meaning: "hundred" },
  { char: "千", pinyin: "qiān", meaning: "thousand" },
  { char: "万", pinyin: "wàn", meaning: "ten thousand" },
  { char: "零", pinyin: "líng", meaning: "zero" },
  { char: "人", pinyin: "rén", meaning: "person" },
  { char: "大", pinyin: "dà", meaning: "big" },
  { char: "小", pinyin: "xiǎo", meaning: "small" },
  { char: "中", pinyin: "zhōng", meaning: "middle / China" },
  { char: "上", pinyin: "shàng", meaning: "up / above" },
  { char: "下", pinyin: "xià", meaning: "down / below" },
  { char: "口", pinyin: "kǒu", meaning: "mouth" },
  { char: "日", pinyin: "rì", meaning: "sun / day" },
  { char: "月", pinyin: "yuè", meaning: "moon / month" },
  { char: "年", pinyin: "nián", meaning: "year" },
  { char: "时", pinyin: "shí", meaning: "time / hour" },
  { char: "天", pinyin: "tiān", meaning: "sky / day" },
  { char: "地", pinyin: "dì", meaning: "earth / ground" },
  { char: "国", pinyin: "guó", meaning: "country" },
  { char: "家", pinyin: "jiā", meaning: "home / family" },
  { char: "学", pinyin: "xué", meaning: "study / learn" },
  { char: "校", pinyin: "xiào", meaning: "school" },
  { char: "生", pinyin: "shēng", meaning: "born / student" },
  { char: "老", pinyin: "lǎo", meaning: "old / elderly" },
  { char: "力", pinyin: "lì", meaning: "strength / power" },
  { char: "心", pinyin: "xīn", meaning: "heart / mind" },
  { char: "手", pinyin: "shǒu", meaning: "hand" },
  { char: "目", pinyin: "mù", meaning: "eye" },
  { char: "文", pinyin: "wén", meaning: "writing / language" },
  { char: "字", pinyin: "zì", meaning: "character / word" },
  { char: "名", pinyin: "míng", meaning: "name / famous" },
  { char: "事", pinyin: "shì", meaning: "matter / thing" },
  { char: "方", pinyin: "fāng", meaning: "direction / square" },
  { char: "面", pinyin: "miàn", meaning: "face / surface" },
  { char: "头", pinyin: "tóu", meaning: "head" },
  { char: "里", pinyin: "lǐ", meaning: "inside / mile" },
  { char: "身", pinyin: "shēn", meaning: "body / self" },
  { char: "气", pinyin: "qì", meaning: "air / breath / spirit" },
  { char: "水", pinyin: "shuǐ", meaning: "water" },
  { char: "火", pinyin: "huǒ", meaning: "fire" },
  { char: "木", pinyin: "mù", meaning: "wood / tree" },
  { char: "金", pinyin: "jīn", meaning: "gold / metal" },
  { char: "山", pinyin: "shān", meaning: "mountain" },
  { char: "田", pinyin: "tián", meaning: "field / farm" },
  { char: "花", pinyin: "huā", meaning: "flower" },
  { char: "草", pinyin: "cǎo", meaning: "grass" },
  { char: "树", pinyin: "shù", meaning: "tree" },
  { char: "雨", pinyin: "yǔ", meaning: "rain" },
  { char: "雪", pinyin: "xuě", meaning: "snow" },
  { char: "风", pinyin: "fēng", meaning: "wind" },
  { char: "云", pinyin: "yún", meaning: "cloud" },
  { char: "光", pinyin: "guāng", meaning: "light" },
  { char: "星", pinyin: "xīng", meaning: "star" },
  { char: "石", pinyin: "shí", meaning: "stone / rock" },
  { char: "土", pinyin: "tǔ", meaning: "earth / soil" },
  { char: "鱼", pinyin: "yú", meaning: "fish" },
  { char: "鸟", pinyin: "niǎo", meaning: "bird" },
  { char: "牛", pinyin: "niú", meaning: "cow / ox" },
  { char: "马", pinyin: "mǎ", meaning: "horse" },
  { char: "羊", pinyin: "yáng", meaning: "sheep / goat" },
  { char: "鸡", pinyin: "jī", meaning: "chicken" },
  { char: "猫", pinyin: "māo", meaning: "cat" },
  { char: "狗", pinyin: "gǒu", meaning: "dog" },
  { char: "虫", pinyin: "chóng", meaning: "insect / bug" },
  { char: "叶", pinyin: "yè", meaning: "leaf" },
  { char: "果", pinyin: "guǒ", meaning: "fruit / result" },
  { char: "根", pinyin: "gēn", meaning: "root" },
  { char: "茶", pinyin: "chá", meaning: "tea" },
  { char: "米", pinyin: "mǐ", meaning: "rice / meter" },
  { char: "路", pinyin: "lù", meaning: "road / path" },
  { char: "门", pinyin: "mén", meaning: "door / gate" },
  { char: "房", pinyin: "fáng", meaning: "room / house" },
  { char: "车", pinyin: "chē", meaning: "car / vehicle" },
  { char: "书", pinyin: "shū", meaning: "book" },
  { char: "音", pinyin: "yīn", meaning: "sound / music" },
  { char: "乐", pinyin: "lè", meaning: "happy / music" },
  { char: "语", pinyin: "yǔ", meaning: "language" },
  { char: "汉", pinyin: "hàn", meaning: "Han Chinese" },
  { char: "英", pinyin: "yīng", meaning: "English / hero" },
  { char: "数", pinyin: "shù", meaning: "number / math" },
  { char: "电", pinyin: "diàn", meaning: "electricity" },
  { char: "话", pinyin: "huà", meaning: "speech / talk" },
  { char: "工", pinyin: "gōng", meaning: "work / labor" },
  { char: "色", pinyin: "sè", meaning: "color" },
  { char: "点", pinyin: "diǎn", meaning: "point / dot / a bit" },
  { char: "线", pinyin: "xiàn", meaning: "line / thread" },
  { char: "角", pinyin: "jiǎo", meaning: "angle / corner" },
  { char: "圆", pinyin: "yuán", meaning: "circle / round" },
  { char: "半", pinyin: "bàn", meaning: "half" },
  { char: "我", pinyin: "wǒ", meaning: "I / me" },
  { char: "你", pinyin: "nǐ", meaning: "you" },
  { char: "他", pinyin: "tā", meaning: "he / him" },
  { char: "她", pinyin: "tā", meaning: "she / her" },
  { char: "它", pinyin: "tā", meaning: "it" },
  { char: "们", pinyin: "men", meaning: "plural suffix" },
  { char: "的", pinyin: "de", meaning: "particle (possessive)" },
  { char: "了", pinyin: "le", meaning: "particle (completion)" },
  { char: "在", pinyin: "zài", meaning: "at / in / exist" },
  { char: "是", pinyin: "shì", meaning: "to be / is" },
  { char: "有", pinyin: "yǒu", meaning: "have / there is" },
  { char: "和", pinyin: "hé", meaning: "and / with" },
  { char: "就", pinyin: "jiù", meaning: "just / then" },
  { char: "也", pinyin: "yě", meaning: "also / too" },
  { char: "都", pinyin: "dōu", meaning: "all / both" },
  { char: "很", pinyin: "hěn", meaning: "very" },
  { char: "最", pinyin: "zuì", meaning: "most" },
  { char: "还", pinyin: "hái", meaning: "still / also" },
  { char: "再", pinyin: "zài", meaning: "again" },
  { char: "又", pinyin: "yòu", meaning: "again / both" },
  { char: "已", pinyin: "yǐ", meaning: "already" },
  { char: "被", pinyin: "bèi", meaning: "by (passive marker)" },
  { char: "让", pinyin: "ràng", meaning: "let / allow" },
  { char: "把", pinyin: "bǎ", meaning: "hold / particle" },
  { char: "给", pinyin: "gěi", meaning: "give / for" },
  { char: "从", pinyin: "cóng", meaning: "from" },
  { char: "到", pinyin: "dào", meaning: "arrive / to" },
  { char: "对", pinyin: "duì", meaning: "correct / toward" },
  { char: "与", pinyin: "yǔ", meaning: "and / with" },
  { char: "或", pinyin: "huò", meaning: "or" },
  { char: "而", pinyin: "ér", meaning: "and / but" },
  { char: "但", pinyin: "dàn", meaning: "but" },
  { char: "因", pinyin: "yīn", meaning: "because" },
  { char: "所", pinyin: "suǒ", meaning: "place / so" },
  { char: "为", pinyin: "wéi", meaning: "for / because" },
  { char: "以", pinyin: "yǐ", meaning: "with / by" },
  { char: "按", pinyin: "àn", meaning: "press / according to" },
  { char: "如", pinyin: "rú", meaning: "as / like" },
  { char: "何", pinyin: "hé", meaning: "what / how" },
  { char: "其", pinyin: "qí", meaning: "its / that" },
  { char: "之", pinyin: "zhī", meaning: "particle (literary)" },
  { char: "乎", pinyin: "hū", meaning: "question particle" },
  { char: "说", pinyin: "shuō", meaning: "say / speak" },
  { char: "看", pinyin: "kàn", meaning: "look / watch" },
  { char: "想", pinyin: "xiǎng", meaning: "think / want" },
  { char: "知", pinyin: "zhī", meaning: "know" },
  { char: "道", pinyin: "dào", meaning: "way / road" },
  { char: "会", pinyin: "huì", meaning: "can / know how" },
  { char: "能", pinyin: "néng", meaning: "can / able to" },
  { char: "要", pinyin: "yào", meaning: "want / need" },
  { char: "用", pinyin: "yòng", meaning: "use" },
  { char: "做", pinyin: "zuò", meaning: "do / make" },
  { char: "吃", pinyin: "chī", meaning: "eat" },
  { char: "喝", pinyin: "hē", meaning: "drink" },
  { char: "睡", pinyin: "shuì", meaning: "sleep" },
  { char: "跑", pinyin: "pǎo", meaning: "run" },
  { char: "走", pinyin: "zǒu", meaning: "walk / go" },
  { char: "坐", pinyin: "zuò", meaning: "sit" },
  { char: "站", pinyin: "zhàn", meaning: "stand / station" },
  { char: "开", pinyin: "kāi", meaning: "open / start" },
  { char: "关", pinyin: "guān", meaning: "close / off" },
  { char: "写", pinyin: "xiě", meaning: "write" },
  { char: "听", pinyin: "tīng", meaning: "listen" },
  { char: "问", pinyin: "wèn", meaning: "ask" },
  { char: "答", pinyin: "dá", meaning: "answer" },
  { char: "教", pinyin: "jiāo", meaning: "teach" },
  { char: "买", pinyin: "mǎi", meaning: "buy" },
  { char: "卖", pinyin: "mài", meaning: "sell" },
  { char: "送", pinyin: "sòng", meaning: "send / deliver" },
  { char: "拿", pinyin: "ná", meaning: "take / hold" },
  { char: "打", pinyin: "dǎ", meaning: "hit / beat / call" },
  { char: "叫", pinyin: "jiào", meaning: "call / shout" },
  { char: "找", pinyin: "zhǎo", meaning: "look for" },
  { char: "带", pinyin: "dài", meaning: "bring / belt" },
  { char: "放", pinyin: "fàng", meaning: "put / release" },
  { char: "进", pinyin: "jìn", meaning: "enter" },
  { char: "出", pinyin: "chū", meaning: "exit / out" },
  { char: "回", pinyin: "huí", meaning: "return" },
  { char: "过", pinyin: "guò", meaning: "pass / over" },
  { char: "起", pinyin: "qǐ", meaning: "rise / start" },
  { char: "来", pinyin: "lái", meaning: "come" },
  { char: "去", pinyin: "qù", meaning: "go" },
  { char: "见", pinyin: "jiàn", meaning: "see / meet" },
  { char: "读", pinyin: "dú", meaning: "read" },
  { char: "画", pinyin: "huà", meaning: "draw / painting" },
  { char: "唱", pinyin: "chàng", meaning: "sing" },
  { char: "玩", pinyin: "wán", meaning: "play" },
  { char: "跳", pinyin: "tiào", meaning: "jump / dance" },
  { char: "笑", pinyin: "xiào", meaning: "laugh / smile" },
  { char: "哭", pinyin: "kū", meaning: "cry" },
  { char: "感", pinyin: "gǎn", meaning: "feel / sense" },
  { char: "爱", pinyin: "ài", meaning: "love" },
  { char: "恨", pinyin: "hèn", meaning: "hate" },
  { char: "帮", pinyin: "bāng", meaning: "help" },
  { char: "告", pinyin: "gào", meaning: "tell / inform" },
  { char: "诉", pinyin: "sù", meaning: "tell / accuse" },
  { char: "请", pinyin: "qǐng", meaning: "please / invite" },
  { char: "谢", pinyin: "xiè", meaning: "thank" },
  { char: "拜", pinyin: "bài", meaning: "worship / visit" },
  { char: "祝", pinyin: "zhù", meaning: "wish / celebrate" },
  { char: "希", pinyin: "xī", meaning: "hope" },
  { char: "望", pinyin: "wàng", meaning: "hope / look" },
  { char: "相", pinyin: "xiāng", meaning: "mutual / each other" },
  { char: "信", pinyin: "xìn", meaning: "believe / letter" },
  { char: "试", pinyin: "shì", meaning: "try / test" },
  { char: "借", pinyin: "jiè", meaning: "borrow / lend" },
  { char: "选", pinyin: "xuǎn", meaning: "choose / select" },
  { char: "决", pinyin: "jué", meaning: "decide" },
  { char: "定", pinyin: "dìng", meaning: "decide / fixed" },
  { char: "成", pinyin: "chéng", meaning: "become / succeed" },
  { char: "败", pinyin: "bài", meaning: "fail / defeat" },
  { char: "赢", pinyin: "yíng", meaning: "win" },
  { char: "输", pinyin: "shū", meaning: "lose" },
  { char: "比", pinyin: "bǐ", meaning: "compare / than" },
  { char: "赛", pinyin: "sài", meaning: "compete / match" },
  { char: "参", pinyin: "cān", meaning: "participate" },
  { char: "加", pinyin: "jiā", meaning: "add / join" },
  { char: "始", pinyin: "shǐ", meaning: "begin / start" },
  { char: "结", pinyin: "jié", meaning: "end / tie" },
  { char: "束", pinyin: "shù", meaning: "bundle / end" },
  { char: "完", pinyin: "wán", meaning: "finish" },
  { char: "准", pinyin: "zhǔn", meaning: "accurate / allow" },
  { char: "备", pinyin: "bèi", meaning: "prepare" },
  { char: "计", pinyin: "jì", meaning: "plan / calculate" },
  { char: "划", pinyin: "huá", meaning: "plan / stroke" },
  { char: "安", pinyin: "ān", meaning: "peaceful / safe" },
  { char: "排", pinyin: "pái", meaning: "arrange / row" },
  { char: "管", pinyin: "guǎn", meaning: "manage / tube" },
  { char: "理", pinyin: "lǐ", meaning: "manage / reason" },
  { char: "解", pinyin: "jiě", meaning: "understand / solve" },
  { char: "处", pinyin: "chǔ", meaning: "handle / place" },
  { char: "分", pinyin: "fēn", meaning: "minute / score / divide" },
  { char: "析", pinyin: "xī", meaning: "analyze" },
  { char: "研", pinyin: "yán", meaning: "research / grind" },
  { char: "究", pinyin: "jiū", meaning: "research" },
  { char: "调", pinyin: "diào", meaning: "investigate / tune" },
  { char: "查", pinyin: "chá", meaning: "investigate / check" },
  { char: "发", pinyin: "fā", meaning: "send / develop" },
  { char: "现", pinyin: "xiàn", meaning: "appear / now" },
  { char: "证", pinyin: "zhèng", meaning: "prove / certificate" },
  { char: "明", pinyin: "míng", meaning: "bright / tomorrow" },
  { char: "好", pinyin: "hǎo", meaning: "good / well" },
  { char: "不", pinyin: "bù", meaning: "not / no" },
  { char: "这", pinyin: "zhè", meaning: "this" },
  { char: "那", pinyin: "nà", meaning: "that" },
  { char: "多", pinyin: "duō", meaning: "many / much" },
  { char: "少", pinyin: "shǎo", meaning: "few / little" },
  { char: "几", pinyin: "jǐ", meaning: "how many / a few" },
  { char: "两", pinyin: "liǎng", meaning: "two (of)" },
  { char: "早", pinyin: "zǎo", meaning: "early / morning" },
  { char: "晚", pinyin: "wǎn", meaning: "evening / late" },
  { char: "今", pinyin: "jīn", meaning: "now / today" },
  { char: "红", pinyin: "hóng", meaning: "red" },
  { char: "绿", pinyin: "lǜ", meaning: "green" },
  { char: "蓝", pinyin: "lán", meaning: "blue" },
  { char: "黄", pinyin: "huáng", meaning: "yellow" },
  { char: "白", pinyin: "bái", meaning: "white" },
  { char: "黑", pinyin: "hēi", meaning: "black" },
  { char: "高", pinyin: "gāo", meaning: "tall / high" },
  { char: "低", pinyin: "dī", meaning: "low / short" },
  { char: "冷", pinyin: "lěng", meaning: "cold" },
  { char: "热", pinyin: "rè", meaning: "hot" },
  { char: "新", pinyin: "xīn", meaning: "new" },
  { char: "快", pinyin: "kuài", meaning: "fast / quick" },
  { char: "慢", pinyin: "màn", meaning: "slow" },
  { char: "长", pinyin: "cháng", meaning: "long" },
  { char: "短", pinyin: "duǎn", meaning: "short" },
  { char: "重", pinyin: "zhòng", meaning: "heavy / important" },
  { char: "轻", pinyin: "qīng", meaning: "light / gentle" },
  { char: "硬", pinyin: "yìng", meaning: "hard / stiff" },
  { char: "软", pinyin: "ruǎn", meaning: "soft" },
  { char: "甜", pinyin: "tián", meaning: "sweet" },
  { char: "苦", pinyin: "kǔ", meaning: "bitter" },
  { char: "辣", pinyin: "là", meaning: "spicy" },
  { char: "咸", pinyin: "xián", meaning: "salty" },
  { char: "酸", pinyin: "suān", meaning: "sour" },
  { char: "香", pinyin: "xiāng", meaning: "fragrant / delicious" },
  { char: "臭", pinyin: "chòu", meaning: "smelly" },
  { char: "亮", pinyin: "liàng", meaning: "bright" },
  { char: "暗", pinyin: "àn", meaning: "dark" },
  { char: "美", pinyin: "měi", meaning: "beautiful / America" },
  { char: "丑", pinyin: "chǒu", meaning: "ugly" },
  { char: "错", pinyin: "cuò", meaning: "wrong / mistake" },
  { char: "真", pinyin: "zhēn", meaning: "true / real" },
  { char: "假", pinyin: "jiǎ", meaning: "fake / false" },
  { char: "容", pinyin: "róng", meaning: "contain / allow" },
  { char: "易", pinyin: "yì", meaning: "easy" },
  { char: "难", pinyin: "nán", meaning: "difficult" },
  { char: "简", pinyin: "jiǎn", meaning: "simple" },
  { char: "单", pinyin: "dān", meaning: "single / simple" },
  { char: "复", pinyin: "fù", meaning: "repeat / complex" },
  { char: "杂", pinyin: "zá", meaning: "mixed / complex" },
  { char: "趣", pinyin: "qù", meaning: "interest / fun" },
  { char: "无", pinyin: "wú", meaning: "without / none" },
  { char: "聊", pinyin: "liáo", meaning: "chat / boring" },
  { char: "健", pinyin: "jiàn", meaning: "healthy / strong" },
  { char: "康", pinyin: "kāng", meaning: "health" },
  { char: "全", pinyin: "quán", meaning: "complete / whole" },
  { char: "危", pinyin: "wēi", meaning: "danger" },
  { char: "险", pinyin: "xiǎn", meaning: "danger /险峻" },
  { char: "普", pinyin: "pǔ", meaning: "universal / common" },
  { char: "通", pinyin: "tōng", meaning: "through / communicate" },
  { char: "特", pinyin: "tè", meaning: "special" },
  { char: "别", pinyin: "bié", meaning: "other / don't" },
  { char: "样", pinyin: "yàng", meaning: "manner / kind" },
  { char: "干", pinyin: "gān", meaning: "dry / clean" },
  { char: "净", pinyin: "jìng", meaning: "clean" },
  { char: "脏", pinyin: "zāng", meaning: "dirty" },
  { char: "整", pinyin: "zhěng", meaning: "whole / tidy" },
  { char: "洁", pinyin: "jié", meaning: "clean" },
  { char: "乱", pinyin: "luàn", meaning: "messy / chaotic" },
  { char: "直", pinyin: "zhí", meaning: "straight" },
  { char: "弯", pinyin: "wān", meaning: "bend / curve" },
  { char: "平", pinyin: "píng", meaning: "flat / peaceful" },
  { char: "斜", pinyin: "xié", meaning: "slanted / diagonal" },
  { char: "深", pinyin: "shēn", meaning: "deep" },
  { char: "浅", pinyin: "qiǎn", meaning: "shallow" },
  { char: "前", pinyin: "qián", meaning: "front / before" },
  { char: "后", pinyin: "hòu", meaning: "back / after" },
  { char: "左", pinyin: "zuǒ", meaning: "left" },
  { char: "右", pinyin: "yòu", meaning: "right" },
  { char: "东", pinyin: "dōng", meaning: "east" },
  { char: "西", pinyin: "xī", meaning: "west" },
  { char: "南", pinyin: "nán", meaning: "south" },
  { char: "北", pinyin: "běi", meaning: "north" },
  { char: "昨", pinyin: "zuó", meaning: "yesterday" },
  { char: "午", pinyin: "wǔ", meaning: "noon / midday" },
  { char: "周", pinyin: "zhōu", meaning: "week / cycle" },
  { char: "秒", pinyin: "miǎo", meaning: "second (time)" },
  { char: "将", pinyin: "jiāng", meaning: "will / general" },
  { char: "近", pinyin: "jìn", meaning: "near / recent" },
  { char: "经", pinyin: "jīng", meaning: "pass through / classic" },
  { char: "常", pinyin: "cháng", meaning: "often / normal" },
  { char: "偶", pinyin: "ǒu", meaning: "occasional / pair" },
  { char: "尔", pinyin: "ěr", meaning: "you (literary)" },
  { char: "每", pinyin: "měi", meaning: "every / each" },
  { char: "春", pinyin: "chūn", meaning: "spring" },
  { char: "夏", pinyin: "xià", meaning: "summer" },
  { char: "秋", pinyin: "qiū", meaning: "autumn / fall" },
  { char: "冬", pinyin: "dōng", meaning: "winter" },
  { char: "节", pinyin: "jié", meaning: "festival / joint" },
  { char: "城", pinyin: "chéng", meaning: "city" },
  { char: "市", pinyin: "shì", meaning: "city / market" },
  { char: "省", pinyin: "shěng", meaning: "province" },
  { char: "区", pinyin: "qū", meaning: "district / area" },
  { char: "街", pinyin: "jiē", meaning: "street" },
  { char: "楼", pinyin: "lóu", meaning: "building / floor" },
  { char: "层", pinyin: "céng", meaning: "floor / layer" },
  { char: "室", pinyin: "shì", meaning: "room" },
  { char: "院", pinyin: "yuàn", meaning: "courtyard / institution" },
  { char: "园", pinyin: "yuán", meaning: "garden / park" },
  { char: "馆", pinyin: "guǎn", meaning: "hall / building" },
  { char: "店", pinyin: "diàn", meaning: "shop / store" },
  { char: "场", pinyin: "chǎng", meaning: "place / field" },
  { char: "港", pinyin: "gǎng", meaning: "harbor / Hong Kong" },
  { char: "机", pinyin: "jī", meaning: "machine / aircraft" },
  { char: "医", pinyin: "yī", meaning: "medicine / doctor" },
  { char: "银", pinyin: "yín", meaning: "silver / bank" },
  { char: "行", pinyin: "háng", meaning: "business / bank" },
  { char: "超", pinyin: "chāo", meaning: "exceed / super" },
  { char: "公", pinyin: "gōng", meaning: "public" },
  { char: "司", pinyin: "sī", meaning: "manage / department" },
  { char: "厂", pinyin: "chǎng", meaning: "factory" },
  { char: "农", pinyin: "nóng", meaning: "agriculture / farmer" },
  { char: "村", pinyin: "cūn", meaning: "village" },
  { char: "外", pinyin: "wài", meaning: "outside / foreign" },
  { char: "海", pinyin: "hǎi", meaning: "sea / ocean" },
  { char: "世", pinyin: "shì", meaning: "world / generation" },
  { char: "界", pinyin: "jiè", meaning: "boundary / world" },
  { char: "球", pinyin: "qiú", meaning: "ball / earth" },
  { char: "宇", pinyin: "yǔ", meaning: "universe / space" },
  { char: "宙", pinyin: "zhòu", meaning: "universe / time" },
  { char: "父", pinyin: "fù", meaning: "father" },
  { char: "母", pinyin: "mǔ", meaning: "mother" },
  { char: "朋", pinyin: "péng", meaning: "friend" },
  { char: "友", pinyin: "yǒu", meaning: "friend" },
  { char: "兄", pinyin: "xiōng", meaning: "older brother" },
  { char: "弟", pinyin: "dì", meaning: "younger brother" },
  { char: "姐", pinyin: "jiě", meaning: "older sister" },
  { char: "妹", pinyin: "mèi", meaning: "younger sister" },
  { char: "儿", pinyin: "ér", meaning: "child / son" },
  { char: "女", pinyin: "nǚ", meaning: "female / daughter" },
  { char: "夫", pinyin: "fū", meaning: "husband" },
  { char: "妻", pinyin: "qī", meaning: "wife" },
  { char: "子", pinyin: "zǐ", meaning: "child / son" },
  { char: "孙", pinyin: "sūn", meaning: "grandchild" },
  { char: "祖", pinyin: "zǔ", meaning: "ancestor" },
  { char: "爷", pinyin: "yé", meaning: "grandpa / sir" },
  { char: "奶", pinyin: "nǎi", meaning: "grandma / milk" },
  { char: "叔", pinyin: "shū", meaning: "uncle (father's younger brother)" },
  { char: "伯", pinyin: "bó", meaning: "uncle (father's older brother)" },
  { char: "姑", pinyin: "gū", meaning: "aunt (father's sister)" },
  { char: "舅", pinyin: "jiù", meaning: "uncle (mother's brother)" },
  { char: "婶", pinyin: "shěn", meaning: "aunt (uncle's wife)" },
  { char: "侄", pinyin: "zhí", meaning: "nephew / niece" },
  { char: "婆", pinyin: "pó", meaning: "grandma / old woman" },
  { char: "脸", pinyin: "liǎn", meaning: "face" },
  { char: "眼", pinyin: "yǎn", meaning: "eye" },
  { char: "耳", pinyin: "ěr", meaning: "ear" },
  { char: "鼻", pinyin: "bí", meaning: "nose" },
  { char: "嘴", pinyin: "zuǐ", meaning: "mouth / beak" },
  { char: "牙", pinyin: "yá", meaning: "tooth" },
  { char: "舌", pinyin: "shé", meaning: "tongue" },
  { char: "颈", pinyin: "jǐng", meaning: "neck" },
  { char: "肩", pinyin: "jiān", meaning: "shoulder" },
  { char: "胸", pinyin: "xiōng", meaning: "chest" },
  { char: "腰", pinyin: "yāo", meaning: "waist" },
  { char: "背", pinyin: "bèi", meaning: "back" },
  { char: "腿", pinyin: "tuǐ", meaning: "leg" },
  { char: "脚", pinyin: "jiǎo", meaning: "foot" },
  { char: "指", pinyin: "zhǐ", meaning: "finger / point" },
  { char: "甲", pinyin: "jiǎ", meaning: "nail / first" },
  { char: "皮", pinyin: "pí", meaning: "skin / leather" },
  { char: "肤", pinyin: "fū", meaning: "skin" },
  { char: "骨", pinyin: "gǔ", meaning: "bone" },
  { char: "血", pinyin: "xuè", meaning: "blood" },
  { char: "肉", pinyin: "ròu", meaning: "meat / flesh" },
  { char: "肺", pinyin: "fèi", meaning: "lung" },
  { char: "胃", pinyin: "wèi", meaning: "stomach" },
  { char: "脑", pinyin: "nǎo", meaning: "brain" },
  { char: "神", pinyin: "shén", meaning: "spirit / god" },
  { char: "饭", pinyin: "fàn", meaning: "cooked rice / meal" },
  { char: "菜", pinyin: "cài", meaning: "vegetable / dish" },
  { char: "蛋", pinyin: "dàn", meaning: "egg" },
  { char: "粥", pinyin: "zhōu", meaning: "porridge / congee" },
  { char: "汤", pinyin: "tāng", meaning: "soup" },
  { char: "包", pinyin: "bāo", meaning: "bun / bag" },
  { char: "糕", pinyin: "gāo", meaning: "cake / pastry" },
  { char: "饼", pinyin: "bǐng", meaning: "flatbread / cookie" },
  { char: "糖", pinyin: "táng", meaning: "sugar / candy" },
  { char: "盐", pinyin: "yán", meaning: "salt" },
  { char: "油", pinyin: "yóu", meaning: "oil" },
  { char: "酱", pinyin: "jiàng", meaning: "sauce" },
  { char: "醋", pinyin: "cù", meaning: "vinegar" },
  { char: "蒜", pinyin: "suàn", meaning: "garlic" },
  { char: "姜", pinyin: "jiāng", meaning: "ginger" },
  { char: "葱", pinyin: "cōng", meaning: "green onion" },
  { char: "椒", pinyin: "jiāo", meaning: "pepper" },
  { char: "豆", pinyin: "dòu", meaning: "bean" },
  { char: "腐", pinyin: "fǔ", meaning: "tofu / rotten" },
  { char: "虾", pinyin: "xiā", meaning: "shrimp" },
  { char: "蟹", pinyin: "xiè", meaning: "crab" },
  { char: "猪", pinyin: "zhū", meaning: "pig" },
  { char: "衣", pinyin: "yī", meaning: "clothes" },
  { char: "服", pinyin: "fú", meaning: "clothes / serve" },
  { char: "裤", pinyin: "kù", meaning: "pants / trousers" },
  { char: "裙", pinyin: "qún", meaning: "skirt" },
  { char: "帽", pinyin: "mào", meaning: "hat" },
  { char: "鞋", pinyin: "xié", meaning: "shoe" },
  { char: "袜", pinyin: "wà", meaning: "sock" },
  { char: "领", pinyin: "lǐng", meaning: "lead / collar" },
  { char: "袖", pinyin: "xiù", meaning: "sleeve" },
  { char: "扣", pinyin: "kòu", meaning: "button / fasten" },
  { char: "布", pinyin: "bù", meaning: "cloth / fabric" },
  { char: "棉", pinyin: "mián", meaning: "cotton" },
  { char: "船", pinyin: "chuán", meaning: "boat / ship" },
  { char: "飞", pinyin: "fēi", meaning: "fly" },
  { char: "铁", pinyin: "tiě", meaning: "iron / railway" },
  { char: "交", pinyin: "jiāo", meaning: "exchange / traffic" },
  { char: "租", pinyin: "zū", meaning: "rent" },
  { char: "摩", pinyin: "mó", meaning: "rub / motor" },
  { char: "托", pinyin: "tuō", meaning: "hold up / trust" },
  { char: "考", pinyin: "kǎo", meaning: "test / exam" },
  { char: "绩", pinyin: "jì", meaning: "achievement / grade" },
  { char: "功", pinyin: "gōng", meaning: "achievement / merit" },
  { char: "题", pinyin: "tí", meaning: "topic / problem" },
  { char: "案", pinyin: "àn", meaning: "case / plan" },
  { char: "作", pinyin: "zuò", meaning: "make / work" },
  { char: "业", pinyin: "yè", meaning: "occupation / industry" },
  { char: "课", pinyin: "kè", meaning: "class / lesson" },
  { char: "堂", pinyin: "táng", meaning: "hall / classroom" },
  { char: "师", pinyin: "shī", meaning: "teacher / master" },
  { char: "同", pinyin: "tóng", meaning: "same / together" },
  { char: "识", pinyin: "shí", meaning: "know / knowledge" },
  { char: "验", pinyin: "yàn", meaning: "test / experience" },
  { char: "法", pinyin: "fǎ", meaning: "law / method" },
  { char: "职", pinyin: "zhí", meaning: "position / occupation" },
  { char: "合", pinyin: "hé", meaning: "combine / fit" },
  { char: "展", pinyin: "zhǎn", meaning: "develop / exhibit" },
  { char: "步", pinyin: "bù", meaning: "step / pace" },
  { char: "济", pinyin: "jì", meaning: "economy / help" },
  { char: "贸", pinyin: "mào", meaning: "trade" },
  { char: "价", pinyin: "jià", meaning: "price" },
  { char: "格", pinyin: "gé", meaning: "grid / standard" },
  { char: "收", pinyin: "shōu", meaning: "receive / collect" },
  { char: "入", pinyin: "rù", meaning: "enter" },
  { char: "支", pinyin: "zhī", meaning: "support / branch" },
  { char: "利", pinyin: "lì", meaning: "profit / benefit" },
  { char: "润", pinyin: "rùn", meaning: "moist / profit" },
  { char: "自", pinyin: "zì", meaning: "self / oneself" },
  { char: "然", pinyin: "rán", meaning: "natural / right" },
  { char: "环", pinyin: "huán", meaning: "ring / surround" },
  { char: "境", pinyin: "jìng", meaning: "boundary / environment" },
  { char: "保", pinyin: "bǎo", meaning: "protect" },
  { char: "护", pinyin: "hù", meaning: "protect / guard" },
  { char: "资", pinyin: "zī", meaning: "resources / capital" },
  { char: "源", pinyin: "yuán", meaning: "source" },
  { char: "空", pinyin: "kōng", meaning: "empty / sky" },
  { char: "污", pinyin: "wū", meaning: "pollute / dirty" },
  { char: "染", pinyin: "rǎn", meaning: "dye / infect" },
  { char: "态", pinyin: "tài", meaning: "state / attitude" },
  { char: "候", pinyin: "hòu", meaning: "climate / wait" },
  { char: "温", pinyin: "wēn", meaning: "warm / temperature" },
  { char: "度", pinyin: "dù", meaning: "degree / measure" },
  { char: "湿", pinyin: "shī", meaning: "wet / humid" },
  { char: "压", pinyin: "yā", meaning: "pressure / press" },
  { char: "物", pinyin: "wù", meaning: "thing / object" },
  { char: "种", pinyin: "zhǒng", meaning: "kind / species / plant" },
  { char: "网", pinyin: "wǎng", meaning: "net / internet" },
  { char: "络", pinyin: "luò", meaning: "connect / network" },
  { char: "件", pinyin: "jiàn", meaning: "item / component" },
  { char: "程", pinyin: "chéng", meaning: "journey / procedure" },
  { char: "序", pinyin: "xù", meaning: "order / sequence" },
  { char: "据", pinyin: "jù", meaning: "according to / data" },
  { char: "息", pinyin: "xī", meaning: "rest / news" },
  { char: "科", pinyin: "kē", meaning: "science / department" },
  { char: "技", pinyin: "jì", meaning: "skill / technology" },
  { char: "创", pinyin: "chuàng", meaning: "create" },
  { char: "智", pinyin: "zhì", meaning: "wisdom / intelligent" },
  { char: "器", pinyin: "qì", meaning: "device / container" },
  { char: "联", pinyin: "lián", meaning: "connect / ally" },
  { char: "病", pinyin: "bìng", meaning: "sick / illness" },
  { char: "药", pinyin: "yào", meaning: "medicine" },
  { char: "术", pinyin: "shù", meaning: "skill / art / surgery" },
  { char: "治", pinyin: "zhì", meaning: "govern / treat" },
  { char: "疗", pinyin: "liáo", meaning: "treat / therapy" },
  { char: "检", pinyin: "jiǎn", meaning: "check / inspect" },
  { char: "休", pinyin: "xiū", meaning: "rest" },
  { char: "运", pinyin: "yùn", meaning: "transport / luck" },
  { char: "动", pinyin: "dòng", meaning: "move" },
  { char: "锻", pinyin: "duàn", meaning: "forge / exercise" },
  { char: "炼", pinyin: "liàn", meaning: "smelt / train" },
  { char: "营", pinyin: "yíng", meaning: "camp / manage" },
  { char: "养", pinyin: "yǎng", meaning: "raise / nourish" },
  { char: "维", pinyin: "wéi", meaning: "maintain" },
  { char: "素", pinyin: "sù", meaning: "element / plain" },
  { char: "着", pinyin: "zhe", meaning: "particle (ongoing)" },
  { char: "使", pinyin: "shǐ", meaning: "make / use" },
  { char: "没", pinyin: "méi", meaning: "not have" },
  { char: "系", pinyin: "xì", meaning: "system / relate" },
  { char: "怎", pinyin: "zěn", meaning: "how" },
  { char: "么", pinyin: "me", meaning: "question suffix" },
  { char: "什", pinyin: "shén", meaning: "what" },
  { char: "哪", pinyin: "nǎ", meaning: "which / where" },
  { char: "些", pinyin: "xiē", meaning: "some / a few" },
  { char: "个", pinyin: "gè", meaning: "individual (measure word)" },
  { char: "共", pinyin: "gòng", meaning: "together / total" },
  { char: "太", pinyin: "tài", meaning: "too / extremely" },
  { char: "非", pinyin: "fēi", meaning: "non- / wrong" },
  { char: "极", pinyin: "jí", meaning: "extreme / pole" },
  { char: "当", pinyin: "dāng", meaning: "when / should" },
  { char: "较", pinyin: "jiào", meaning: "compare / relatively" },
  { char: "挺", pinyin: "tǐng", meaning: "quite / stand straight" },
  { char: "差", pinyin: "chà", meaning: "differ / bad" },
];

function normalizePinyin(pinyin) {
  return pinyin.toLowerCase()
    .replace(/[āáǎà]/g, 'a')
    .replace(/[ēéěè]/g, 'e')
    .replace(/[īíǐì]/g, 'i')
    .replace(/[ōóǒò]/g, 'o')
    .replace(/[ūúǔù]/g, 'u')
    .replace(/[ǖǘǚǜ]/g, 'u')
    .split(' / ')[0];
}

// Pre-build indexes at load time so every search is an O(1) map lookup.
// PINYIN_INDEX maps every normalized prefix → array of character indices,
// so typing "ni" instantly resolves without scanning all 552 entries.
const CHAR_INDEX   = {};  // char → index (exact Chinese character lookup)
const PINYIN_INDEX = {};  // normalized prefix → [indices]

CHARACTERS.forEach((item, idx) => {
  CHAR_INDEX[item.char] = idx;

  // Pre-normalize once; store on item so renderSearchResults can reuse it
  const norm = normalizePinyin(item.pinyin);
  item._norm = norm;

  for (let len = 1; len <= norm.length; len++) {
    const prefix = norm.slice(0, len);
    if (!PINYIN_INDEX[prefix]) PINYIN_INDEX[prefix] = [];
    PINYIN_INDEX[prefix].push(idx);
  }
});

function searchCharacters(query) {
  if (!query || query.trim() === '') return [];
  query = query.trim();

  // Exact Chinese character match
  if (/[\u4e00-\u9fff]/.test(query)) {
    const idx = CHAR_INDEX[query];
    return idx !== undefined ? [CHARACTERS[idx]] : [];
  }

  // Prefix pinyin lookup — O(1) map read, no per-character iteration or regex
  const norm = normalizePinyin(query.toLowerCase());
  return (PINYIN_INDEX[norm] || []).map(idx => CHARACTERS[idx]);
}

// Total character count
const TOTAL_CHARACTERS = CHARACTERS.length;
